#!/bin/sh

# Create all folders that are going to be needed
cd ~
mkdir -p .config .local/share .local/state .local/bin .cache personal pictures/wallpapers

# Setup all basic env variables so that nothing gets scattered throughout the homedir
export LESSHISTFILE=-
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export EMACSDIR=${XDG_CONFIG_HOME:-$HOME/.config}/emacs
export CARGO_HOME=${XDG_CONFIG_HOME:-$HOME/.config}/cargo
export ZDOTDIR=${XDG_CONFIG_HOME:-$HOME/.config}/zsh
export HISTFILE=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/histfile
export GPG_TTY=$(tty)
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export NODE_REPL_HISTORY=${XDG_DATA_HOME:-$HOME/.local/share}/node_repl_history
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc 
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
export QT_QPA_PLATFORM=wayland
export MOZ_ENABLE_WAYLAND=1
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_STEP=2

# Lists of pkgs to install a wayland-base distro (for me)
BASE=(base base-devel linux linux-firmware git acpi efibootmgr grub wget curl zsh archlinux-keyring)
AUDIO=(pipewire pipewire-audio pipewire-alsa pipewire-jack pipewire-v4l2 wireplumber pasystray-wayland pavucontrol)
BLUE=(bluez bluez-utils blueman)
NET=(network-manager-applet networkmanager networkmanager-dmenu-git networkmanager-openvpn networkmanager-vpnc)
WAYLAND=(qt5ct qt6-wayland waybar wayland wayland-protocols grim slurp sway sway-input-config swaybg swayidle swaylock swww wl-clipboard wl-color-picker wlrobs-hg xorg-xwayland)
DESKTOP=(fuzzel brightnessctl cbatticon chrony discord dunst dmenu foot firefox fd ripgrep grep man-db less htop mesa neovim nodejs npm openssh stow tlp tmux tree ttf-comic-mono-git unzip vi vim vlc zathura zathura-pdf-poppler zram-generator zsh-autosuggestions zsh-completions zsh-syntax-highlighting)

# Install base pkgs
sudo pacman -S --noconfirm "${BASE[@]}"

# Install PARU
sudo pacman -S --needed base-devel
mkdir ~/tmp
cd ~/tmp
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ~

# Install other pkgs
sudo paru -S --noconfirm "${AUDIO[@]}" "${BLUE[@]}" "${NET[@]}" "${DESKTOP[@]}" "${DESKTOP[@]}"

# Setup git
git config --global user.name "Alfonso Amorós Cubells"
git config --global user.email "alfonso.alfurtx@gmail.com"

# Setup new ssh keys
# Setup shh-agent
# Setup new github keys

# Setup multihead (multi monitor) support
# Setup work if another monitor is connected and lid is closed
